"""
NEXUS — GitHub repo generation (Feature: push a project's generated
files to a brand-new GitHub repository under the authenticated user's
account, or under settings.github_export_token's account as a fallback).

Flow: create repo -> commit each GeneratedFile via the Contents API
(simplest correct approach for a fresh repo; avoids needing a full
git-tree/blob dance for what's usually a few dozen files).
"""
from __future__ import annotations

import base64
import re
from urllib.parse import quote

import httpx
from sqlmodel import select
from sqlmodel.ext.asyncio.session import AsyncSession

from app.core.config import get_settings
from app.core.safe_path import UnsafeGeneratedPath, safe_relative_path
from app.db.models import GeneratedFile

settings = get_settings()
API_BASE = "https://api.github.com"


class GitHubExportError(Exception):
    pass


# GitHub repo names allow letters, digits, hyphens, underscores, and
# dots — anything else (spaces, slashes, control characters) either
# gets silently mangled or breaks the request. Validating up front
# gives a clear error instead of a confusing 422/404 from GitHub.
_REPO_NAME_RE = re.compile(r"^[A-Za-z0-9._-]{1,100}$")


def _validate_repo_name(repo_name: str) -> str:
    if not _REPO_NAME_RE.match(repo_name):
        raise GitHubExportError(
            "Repo name can only contain letters, numbers, dots, hyphens, and underscores."
        )
    return repo_name


async def export_project_to_github(
    session: AsyncSession,
    project_id: str,
    repo_name: str,
    private: bool = True,
    user_access_token: str | None = None,
) -> dict:
    """Creates a new GitHub repo and pushes every GeneratedFile into it.

    `user_access_token` (from the user's own GitHub OAuth login, if
    available) is preferred so the repo lands in their account. Falls
    back to `settings.github_export_token` (a server-side PAT) when the
    user didn't sign in with GitHub.
    """
    repo_name = _validate_repo_name(repo_name)

    token = user_access_token or settings.github_export_token
    if not token:
        raise GitHubExportError(
            "No GitHub token available. Sign in with GitHub, or set GITHUB_EXPORT_TOKEN "
            "on the backend for server-side exports."
        )

    result = await session.exec(select(GeneratedFile).where(GeneratedFile.project_id == project_id))
    files = result.all()
    if not files:
        raise GitHubExportError("This project has no generated files yet — nothing to export.")

    headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"}

    async with httpx.AsyncClient(base_url=API_BASE, headers=headers, timeout=30) as client:
        me = await client.get("/user")
        if me.status_code != 200:
            raise GitHubExportError("GitHub token is invalid or expired.")
        owner = me.json()["login"]

        create_resp = await client.post(
            "/user/repos",
            json={"name": repo_name, "private": private, "auto_init": True,
                  "description": "Generated by NEXUS AI"},
        )
        if create_resp.status_code == 422:
            raise GitHubExportError(f"A repo named '{repo_name}' already exists on your account.")
        if create_resp.status_code not in (200, 201):
            raise GitHubExportError(f"GitHub repo creation failed: {create_resp.text}")
        repo = create_resp.json()

        pushed = 0
        skipped = 0
        for f in files:
            # f.path is LLM-generated and was previously interpolated
            # straight into the URL: unescaped, a path containing "#",
            # "?", or spaces silently truncates or misdirects the
            # request, and a path starting with ".." or "/" could target
            # an unintended location in the repo tree (GitHub's own API
            # validation is the last line of defense there, but this
            # app shouldn't be relying on that alone). Both issues are
            # closed by validating the path with the same
            # safe_relative_path() used for the sandbox and deployment
            # writers, then percent-encoding each segment before it
            # goes into the URL.
            try:
                safe_path = safe_relative_path(f.path)
            except UnsafeGeneratedPath:
                skipped += 1
                continue
            encoded_path = "/".join(quote(seg, safe="") for seg in safe_path.split("/"))

            content_b64 = base64.b64encode(f.content.encode("utf-8")).decode("ascii")
            put_resp = await client.put(
                f"/repos/{owner}/{repo_name}/contents/{encoded_path}",
                json={"message": f"Add {safe_path} (via NEXUS)", "content": content_b64},
            )
            if put_resp.status_code in (200, 201):
                pushed += 1
            # Individual file failures are non-fatal — report a partial
            # export rather than aborting a mostly-successful push.

        return {
            "repo_url": repo["html_url"],
            "clone_url": repo["clone_url"],
            "files_pushed": pushed,
            "files_total": len(files),
            "files_skipped_unsafe_path": skipped,
        }
