"""
NEXUS — GitHub repo generation (Feature: push a project's generated
files to a brand-new GitHub repository under the authenticated user's
account, or under settings.github_export_token's account as a fallback).

Flow: create repo -> commit each GeneratedFile via the Contents API
(simplest correct approach for a fresh repo; avoids needing a full
git-tree/blob dance for what's usually a few dozen files).
"""
from __future__ import annotations

import base64

import httpx
from sqlmodel import select
from sqlmodel.ext.asyncio.session import AsyncSession

from app.core.config import get_settings
from app.db.models import GeneratedFile

settings = get_settings()
API_BASE = "https://api.github.com"


class GitHubExportError(Exception):
    pass


async def export_project_to_github(
    session: AsyncSession,
    project_id: str,
    repo_name: str,
    private: bool = True,
    user_access_token: str | None = None,
) -> dict:
    """Creates a new GitHub repo and pushes every GeneratedFile into it.

    `user_access_token` (from the user's own GitHub OAuth login, if
    available) is preferred so the repo lands in their account. Falls
    back to `settings.github_export_token` (a server-side PAT) when the
    user didn't sign in with GitHub.
    """
    token = user_access_token or settings.github_export_token
    if not token:
        raise GitHubExportError(
            "No GitHub token available. Sign in with GitHub, or set GITHUB_EXPORT_TOKEN "
            "on the backend for server-side exports."
        )

    result = await session.exec(select(GeneratedFile).where(GeneratedFile.project_id == project_id))
    files = result.all()
    if not files:
        raise GitHubExportError("This project has no generated files yet — nothing to export.")

    headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"}

    async with httpx.AsyncClient(base_url=API_BASE, headers=headers, timeout=30) as client:
        me = await client.get("/user")
        if me.status_code != 200:
            raise GitHubExportError("GitHub token is invalid or expired.")
        owner = me.json()["login"]

        create_resp = await client.post(
            "/user/repos",
            json={"name": repo_name, "private": private, "auto_init": True,
                  "description": "Generated by NEXUS AI"},
        )
        if create_resp.status_code == 422:
            raise GitHubExportError(f"A repo named '{repo_name}' already exists on your account.")
        if create_resp.status_code not in (200, 201):
            raise GitHubExportError(f"GitHub repo creation failed: {create_resp.text}")
        repo = create_resp.json()

        pushed = 0
        for f in files:
            content_b64 = base64.b64encode(f.content.encode("utf-8")).decode("ascii")
            put_resp = await client.put(
                f"/repos/{owner}/{repo_name}/contents/{f.path}",
                json={"message": f"Add {f.path} (via NEXUS)", "content": content_b64},
            )
            if put_resp.status_code in (200, 201):
                pushed += 1
            # Individual file failures are non-fatal — report a partial
            # export rather than aborting a mostly-successful push.

        return {
            "repo_url": repo["html_url"],
            "clone_url": repo["clone_url"],
            "files_pushed": pushed,
            "files_total": len(files),
        }
