"""add totp fields to user

Revision ID: 3f086b6e3c11
Revises: eb174659ba7f
Create Date: 2026-09-16 01:32:05.855467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — SQLModel's own column types (e.g. AutoString)
                 # show up in autogenerate output as sqlmodel.sql.sqltypes.*,
                 # but Alembic's default template only imports sqlalchemy —
                 # without this, every migration referencing a SQLModel type
                 # crashes with NameError the moment it actually runs.


# revision identifiers, used by Alembic.
revision: str = '3f086b6e3c11'
down_revision: Union[str, None] = 'eb174659ba7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('totp_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # Bug fix (caught before this shipped, not after): autogenerate
    # produced `nullable=False` with no default. SQLite silently
    # tolerates that even against existing rows, but Postgres — what
    # production actually runs — genuinely REJECTS adding a NOT NULL
    # column with no default to a table that already has rows, which
    # your live `user` table definitely does. server_default gives
    # every existing row a real value at the database level (Python's
    # `Field(default=False)` only applies to rows created afterward
    # through the ORM, not to this ALTER TABLE itself).
    op.add_column('user', sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user', sa.Column('totp_backup_codes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'totp_backup_codes')
    op.drop_column('user', 'totp_enabled')
    op.drop_column('user', 'totp_secret')
    # ### end Alembic commands ###
